### ISSUE TITLE
python 3.7 hex encode fails

### ISSUE THREAD

**Issue by stackdump** [FactomProject/factom-api#7]
https://github.com/FactomProject/factom-api/blob/master/factom/client.py#L645

I'm seeing 
```
    'extids': [hex(x) for x in ext_ids],
TypeError: 'str' object cannot be interpreted as an integer

```
At least in my environment the hex function expects an integer input
https://docs.python.org/3/library/functions.html?highlight=hex#hex

**Comment by sanchopansa** [comment]
This is one of the issues addressed by the open PR

**Comment by stackdump** [comment]
confirmed that using sam's version `pip install -e git://github.com/sambarnes/factom-api.git@sb_BugFixesAndTypeHints#egg=factom-api`  fixes the issue I'm seeing

closing to watch this PR instead https://github.com/FactomProject/factom-api/pull/6
